const http = require('http')
http.request({
        method: 'GET',
        agent: http.Agent({keepAlive:true}),
        host: http://localhost:8080,
    })

###
GET http://localhost:8080
###
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "username" : "alon",
    "email" : "alon@asd.com",
    "password" : "123456",
    "roles" : ["moderator" , "user"]
}
###
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
    "username" : "alon",
    "password" : "123456"
}
###
PUT http://localhost:8080/api/auth/update
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjU4Njg2NTIyLCJleHAiOjE2NTg3MDQ1MjJ9.ROEASI9komfy6WZVxhsqiFPuftEEA7-Ls0t2ybOigx8

{
    "businessName":"flowers"
}

###

###
POST http://localhost:8080/api/auth/signout

###
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "username": "a",
    "email": "a@gmail.com",
    "password": "123456",
    "phoneNumber": "0324567890",
    "businessName": "my Business",
    "businesslogoImg": "",
    "businessAddress": "abc tlv",
    "businessPhoneNumber": "046578954",
    "roles" : ["moderator" , "user"]
}
###
GET http://localhost:8080/api/income/all
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjU1MTM0ODY1LCJleHAiOjE2NTUxMzg0NjV9.yCUvRRxe0zysczKf1BbIRJVz5u2-XLHNf4JFLiSb7BE

###

GET http://193.106.55.113:8080/api/income/total
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjUzNDA1Mjg3LCJleHAiOjE2NTM0MDg4ODd9.s03B07mJBVBhzKnthHo2X1_ORCb9PjGtMZDhzJydvoY

###
GET http://localhost:8080/api/income/grouped-by-months
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjU1MTQ0OTY4LCJleHAiOjE2NTUxNDg1Njh9.OIEMxXOb0MstVoAnVOtKCoegLILo_A9Xo6qgGmROwJ8

 ###

###
GET http://localhost:8080/api/expense/grouped-by-months

 ###

###
GET http://localhost:8080/api/income/sum
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjU1MTkzNDQyLCJleHAiOjE2NTUxOTcwNDJ9.gc71jkKdQdZK2t3mhrI8e0ghxUWfi_uq8KDoC2KmADc
 ###
 
###
GET http://localhost:8080/api/expense/VatSum
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjU1MTUxNDI1LCJleHAiOjE2NTUxNTUwMjV9.1cRI5vcyt9Ew2Aci1-NVpPrp3qAO8rZ7Xpb1KVhDkmE
 ###
 
###
POST http://localhost:8080/api/expense/create
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjU1MTk3MzY4LCJleHAiOjE2NTUyMTUzNjh9.FewyQJmsFLjBrEPysmnuC3fKDA4utjoy_zKK4OedE_Q

{
    "businessId": 1,
    "date": "2022-01-30",
    "name": "1",
    "expenseImg": "1655059404832-xcount-SomeImageName.jpg",
    "expenseSum": 300,
    "currency":"1",
    "VatType": "15",
    "IrsRefund": 1.1,
    "refundSum": 1.1,
    "confirmed": "1"
}

###

GET http://localhost:8080/api/expense/all

###
GET http://localhost:8080/api/127.0.0.1:8080/api/income/sum
###

DELETE  http://localhost:8080/api/expense/delete/1

###
PUT  http://localhost:8080/api/expense/update/1
Content-Type: application/json

{
    "expenseSum":"3000",
    "type":"clothes"
}
###

GET http://xcount.cs.colman.ac.il
####
POST  http://127.0.0.1:8080/api/income/create
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjU1MTk3MzY4LCJleHAiOjE2NTUyMTUzNjh9.FewyQJmsFLjBrEPysmnuC3fKDA4utjoy_zKK4OedE_Q
Content-Type: application/json

{
    "saveCustomer":1,
    "customerId":0,
    "date": "2022-08-10",
    "description": "a",
    "items": [],
    "incomeSum": 100,
    "paymentMethods": []

}

###
POST http://127.0.0.1:8080/api/auth/signin
Content-Type: application/json

{
    "username" : "a",
    "password" : "123456"
}

###

POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
    "username" : "mod",
    "password" : "12345678"
}

###

GET http://localhost:6868/api/test/admin

###

POST http://localhost:6868/api/auth/refreshtoken
Content-Type: application/json

{
    "refreshToken": "6b9579c4-766e-4908-9b91-15521b244a5d"
}


