const http = require('http')
http.request({
        method: 'GET',
        agent: http.Agent({keepAlive:true}),
        host: 'http://localhost:8081',
    })

###
GET http://localhost:8080
Content-Type: application/json

{
 "itemsList": 
    [{
        "itemID": 1,
        "itemName": "a",	
        "price": 12.0,
        "amount": 3,
        "sumPrice": 36.0
    },{
        "itemID": 2,
        "itemName": "b",	
        "price": 13.0,
        "amount": 3,
        "sumPrice": 39.0
    }]
}

###
POST http://localhost:8080/api/auth/signout
###
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "username" : "alon",
    "email" : "alon@asd.com",
    "password" : "123456",
    "roles" : ["moderator" , "user"], 
}
###
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "username" : "sdee",
    "email" : "aafdsfhlon@asd.com",
    "password" : "123456",
    "roles" : ["moderator" , "user"]
}
###

POST http://localhost:8080/api/expense/create
Content-Type: application/json

{
    "businessId": 1,
    "date": "2017-06-15",
    "name": "1",
    "expenseItems": "123",
    "expenseImg": "1",
    "expenseSum": 1.1,
    "currency":"1",
    "VatType": "1",
    "VatRefund": 1.1,
    "IrsRefund": 1.1,
    "refundSum": 1.1,
    "confirmed": "1"
}

###

GET http://localhost:8080/api/expense/all/1

###
GET http://localhost:8080/api/expense/find/1/comp
###

DELETE  http://localhost:8080/api/expense/delete/1

###
PUT  http://localhost:8080/api/expense/update/3
Content-Type: application/json

{
    "expenseSum":"3000",
    "type":"clothes"
}
###
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
    "username" : "sdee",
    "email" : "aafdsfhlon@asd.com",
    "password" : "123456",
    "roles" : ["moderator" , "user"]
}


###

POST http://127.0.0.1:8080/api/auth/signin
Content-Type: application/json

{
    "username" : "alon",
    "password" : "123456"
}

###
GET http://127.0.0.1:8080/api/income/total
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjUzNDA1Mjg3LCJleHAiOjE2NTM0MDg4ODd9.s03B07mJBVBhzKnthHo2X1_ORCb9PjGtMZDhzJydvoY

###
POST  http://127.0.0.1:8080/api/income/create
Content-Type: application/json

{
    "businessId": 1,
    "customerId": 1,
    "date": "2022-01-17",
    "title": "test",
    "incomSum": 125.78,
    "currency": "shekel",
    "incomeType": "Tax invoice",
    "paymentMethod": "Credit"
}

###
POST http://127.0.0.1:8080/api/auth/signin
Content-Type: application/json

{
    "username" : "sdee",
    "password" : "123456"
}

###

POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
    "username" : "mod",
    "password" : "12345678"
}

###

GET http://localhost:6868/api/test/admin

###

POST http://localhost:6868/api/auth/refreshtoken
Content-Type: application/json

{
    "refreshToken": "6b9579c4-766e-4908-9b91-15521b244a5d"
}


